language: rust
rust:
  - nightly
  - stable
addons:
  apt:
    packages:
    - libegl1-mesa-dev
    - libgtk-3-dev
    - libsdl2-dev
    - cmake
script:
  - rustup target add aarch64-unknown-linux-gnu
  - cd simd
  - cargo build --target aarch64-unknown-linux-gnu
  - cd ../geometry
  - cargo build --target  aarch64-unknown-linux-gnu
  - cd ..
  - cargo build
  - cargo test
env:
  global:
    - HARFBUZZ_SYS_NO_PKG_CONFIG=true
notifications:
  webhooks: http://build.servo.org:54856/travis
