[package]
name = "canvas_webgpu_minimal"
version = "0.1.0"
authors = [
    "Patrick Walton <pcwalton@mimiga.net>",
    "Michael Tang <tangmi@uw.edu>"
]
edition = "2018"

[dependencies]
wgpu = "0.5"
winit = "0.22"

[dependencies.pathfinder_canvas]
features = ["pf-text"]
path = "../../canvas"

[dependencies.pathfinder_color]
path = "../../color"

[dependencies.pathfinder_content]
path = "../../content"

[dependencies.pathfinder_geometry]
path = "../../geometry"

[dependencies.pathfinder_gl]
path = "../../gl"

[dependencies.pathfinder_gpu]
path = "../../gpu"

[dependencies.pathfinder_webgpu]
path = "../../webgpu"

[dependencies.pathfinder_renderer]
path = "../../renderer"

[dependencies.pathfinder_resources]
path = "../../resources"
