[package]
name = "pathfinder_metal"
version = "0.5.1"
edition = "2018"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
description = "A simple cross-platform GPU abstraction library: Metal backend"
license = "MIT/Apache-2.0"
repository = "https://github.com/servo/pathfinder"
homepage = "https://github.com/servo/pathfinder"

[dependencies]
bitflags = "1.0"
byteorder = "1.3"
block = "0.1"
cocoa = "0.19"
core-foundation = "0.6"
foreign-types = "0.3"
half = "1.5"
io-surface = "0.12"
libc = "0.2"
metal = "0.17"
objc = "0.2"

[dependencies.pathfinder_geometry]
path = "../geometry"
version = "0.5"

[dependencies.pathfinder_gpu]
path = "../gpu"
version = "0.5"

[dependencies.pathfinder_resources]
path = "../resources"
version = "0.5"

[dependencies.pathfinder_simd]
path = "../simd"
version = "0.5"
